from launch import LaunchDescription
from launch_ros.actions import Node


def generate_launch_description():
    return LaunchDescription([
        Node(
            package='bodyreader',
            executable='torso_trt_demo',
            name='torso_trt_demo',
            output='screen',
            parameters=[
                {
                    'engine_path': '/home/wheeltec/wheeltec_ros2/src/ultralytics_ros2/model/yolo11n_fp16.engine',
                    'image_topic': '/camera/color/image_raw',
                    'annotated_topic': '/torso_trt_demo/image',
                    'detections_topic': '/torso_trt_demo/detections',
                    'state_topic': '/torso_trt_demo/state',
                    'features_topic': '/torso_trt_demo/features',
                    'locked_topic': '/torso_trt_demo/locked_target',
                    'lock_command_topic': '/torso_trt_demo/lock_command',
                    'depth_topic': '/camera/depth/image_raw',
                    'camera_info_topic': '/camera/color/camera_info',
                    'input_width': 640,
                    'input_height': 640,
                    'conf_threshold': 0.45,
                    'nms_iou_threshold': 0.45,
                    'person_class_id': 0,
                    'max_detections': 20,
                    'min_person_area_px': 600.0,
                    'torso_side_crop_ratio': 0.18,
                    'torso_top_ratio': 0.22,
                    'torso_bottom_ratio': 0.68,
                    'upper_color_side_crop_ratio': 0.28,
                    'upper_color_band_top_ratio': 0.00,
                    'upper_color_band_bottom_ratio': 0.50,
                    'upper_color_inner_top_ratio': 0.34,
                    'upper_color_inner_bottom_ratio': 0.84,
                    'lower_color_side_crop_ratio': 0.26,
                    'lower_color_band_top_ratio': 0.50,
                    'lower_color_band_bottom_ratio': 1.00,
                    'lower_color_inner_top_ratio': 0.08,
                    'lower_color_inner_bottom_ratio': 0.44,
                    'publish_annotated': True,
                    'log_image_features': True,
                    'feature_log_period_sec': 1.0,
                    'max_logged_targets': 6,
                    'color_saturation_min': 22.0,
                    'color_value_min': 35.0,
                    'height_smoothing_alpha': 0.35,
                    'enable_depth_height': True,
                    'camera_fy_px': 0.0,
                    'depth_max_age_sec': 0.5,
                    'depth_unit_scale': 0.001,
                    'min_valid_depth_m': 0.20,
                    'max_valid_depth_m': 8.0,
                    'height_reference_m': 0.0,
                    'height_reference_px': 0.0,
                    'auto_lock_center': False,
                    'track_max_missed': 12,
                    'track_match_threshold': 0.82,
                    'track_iou_weight': 0.35,
                    'track_appearance_weight': 0.35,
                    'track_size_weight': 0.15,
                    'track_center_weight': 0.15,
                }
            ],
        ),
    ])
