#BNF+IAT 1.0 UTF-8;
!grammar call;

!slot <command>;

!start <callstart>;

<callstart>:<command>;
<command>:小车前进|小车后退|小车左转|小车右转|小车停|小车休眠|小车过来|小车去I点|小车去J点|小车去K点|小车雷达跟随|关闭雷达跟随|开启导航|取消导航|开始跟随|开启跟随|取消跟随|关闭跟随|小车回充|取消回充|开始建图|暂停建图|结束建图|保存地图|继续建图;
